a = input('Digite algo:')
print('O tipo primitivo desse valor e', type(a))
print('So tem espasso?', a.isspace())
print('E um numero?', a.isnumeric())
print('E alfabeto?', a.isalpha())
print('E alfanumerico?', a.isnumeric())
print('Esta em maiusclula', a.isupper())
print('Esta em menusclula?', a.islower())
print('Esta capitalizado?', a.istitle())